/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssignmentType = IDL.Variant({
  'specificMembers' : IDL.Vec(IDL.Principal),
  'allMembers' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BootstrapAdminResult = IDL.Variant({
  'adminAlreadyExists' : IDL.Null,
  'success' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const GoalStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'onHold' : IDL.Null,
});
export const DevelopmentPlan = IDL.Record({
  'id' : IDL.Nat,
  'status' : GoalStatus,
  'assignment' : AssignmentType,
  'createdBy' : IDL.Principal,
  'dueDate' : Time,
  'description' : IDL.Text,
});
export const FeedbackItem = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'assignment' : AssignmentType,
  'from' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : Time,
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'status' : GoalStatus,
  'title' : IDL.Text,
  'assignment' : AssignmentType,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'deadline' : Time,
  'progress' : IDL.Nat,
});
export const PerformanceReview = IDL.Record({
  'id' : IDL.Nat,
  'assignment' : AssignmentType,
  'peerAssessment' : IDL.Vec(IDL.Text),
  'selfAssessment' : IDL.Vec(IDL.Text),
  'submittedBy' : IDL.Principal,
  'templateName' : IDL.Text,
  'managerAssessment' : IDL.Vec(IDL.Text),
  'questions' : IDL.Vec(IDL.Text),
});
export const SkillRating = IDL.Record({
  'user' : IDL.Principal,
  'rating' : IDL.Nat,
  'competencyId' : IDL.Nat,
});
export const Competency = IDL.Record({
  'id' : IDL.Nat,
  'assignment' : AssignmentType,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCompetency' : IDL.Func(
      [IDL.Text, IDL.Text, AssignmentType],
      [IDL.Nat],
      [],
    ),
  'addFeedback' : IDL.Func(
      [IDL.Principal, IDL.Text, AssignmentType],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapAdmin' : IDL.Func([], [BootstrapAdminResult], []),
  'createDevelopmentPlan' : IDL.Func(
      [IDL.Text, Time, AssignmentType],
      [IDL.Nat],
      [],
    ),
  'createGoal' : IDL.Func(
      [IDL.Text, IDL.Text, Time, AssignmentType],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDevelopmentPlansForUser' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'assignedToAll' : IDL.Vec(DevelopmentPlan),
          'assignedToMe' : IDL.Vec(DevelopmentPlan),
        }),
      ],
      ['query'],
    ),
  'getFeedbackForUser' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'assignedToAll' : IDL.Vec(FeedbackItem),
          'assignedToMe' : IDL.Vec(FeedbackItem),
        }),
      ],
      ['query'],
    ),
  'getFeedbackFromUser' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'assignedToAll' : IDL.Vec(FeedbackItem),
          'assignedToMe' : IDL.Vec(FeedbackItem),
        }),
      ],
      ['query'],
    ),
  'getGoal' : IDL.Func([IDL.Nat], [IDL.Opt(Goal)], ['query']),
  'getPerformanceReview' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PerformanceReview)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSkillRatings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SkillRating)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCompetencies' : IDL.Func(
      [],
      [
        IDL.Record({
          'assignedToAll' : IDL.Vec(Competency),
          'assignedToMe' : IDL.Vec(Competency),
        }),
      ],
      ['query'],
    ),
  'listGoals' : IDL.Func(
      [],
      [
        IDL.Record({
          'assignedToAll' : IDL.Vec(Goal),
          'assignedToMe' : IDL.Vec(Goal),
        }),
      ],
      ['query'],
    ),
  'listPerformanceReviews' : IDL.Func(
      [],
      [
        IDL.Record({
          'assignedToAll' : IDL.Vec(PerformanceReview),
          'assignedToMe' : IDL.Vec(PerformanceReview),
        }),
      ],
      ['query'],
    ),
  'listUpcomingGoals' : IDL.Func(
      [],
      [
        IDL.Record({
          'assignedToAll' : IDL.Vec(Goal),
          'assignedToMe' : IDL.Vec(Goal),
        }),
      ],
      ['query'],
    ),
  'rateSkill' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPerformanceReview' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        AssignmentType,
      ],
      [IDL.Nat],
      [],
    ),
  'updateDevelopmentPlanStatus' : IDL.Func([IDL.Nat, GoalStatus], [], []),
  'updateGoalStatus' : IDL.Func([IDL.Nat, GoalStatus, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssignmentType = IDL.Variant({
    'specificMembers' : IDL.Vec(IDL.Principal),
    'allMembers' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BootstrapAdminResult = IDL.Variant({
    'adminAlreadyExists' : IDL.Null,
    'success' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const GoalStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const DevelopmentPlan = IDL.Record({
    'id' : IDL.Nat,
    'status' : GoalStatus,
    'assignment' : AssignmentType,
    'createdBy' : IDL.Principal,
    'dueDate' : Time,
    'description' : IDL.Text,
  });
  const FeedbackItem = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'assignment' : AssignmentType,
    'from' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : Time,
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'status' : GoalStatus,
    'title' : IDL.Text,
    'assignment' : AssignmentType,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'deadline' : Time,
    'progress' : IDL.Nat,
  });
  const PerformanceReview = IDL.Record({
    'id' : IDL.Nat,
    'assignment' : AssignmentType,
    'peerAssessment' : IDL.Vec(IDL.Text),
    'selfAssessment' : IDL.Vec(IDL.Text),
    'submittedBy' : IDL.Principal,
    'templateName' : IDL.Text,
    'managerAssessment' : IDL.Vec(IDL.Text),
    'questions' : IDL.Vec(IDL.Text),
  });
  const SkillRating = IDL.Record({
    'user' : IDL.Principal,
    'rating' : IDL.Nat,
    'competencyId' : IDL.Nat,
  });
  const Competency = IDL.Record({
    'id' : IDL.Nat,
    'assignment' : AssignmentType,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCompetency' : IDL.Func(
        [IDL.Text, IDL.Text, AssignmentType],
        [IDL.Nat],
        [],
      ),
    'addFeedback' : IDL.Func(
        [IDL.Principal, IDL.Text, AssignmentType],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapAdmin' : IDL.Func([], [BootstrapAdminResult], []),
    'createDevelopmentPlan' : IDL.Func(
        [IDL.Text, Time, AssignmentType],
        [IDL.Nat],
        [],
      ),
    'createGoal' : IDL.Func(
        [IDL.Text, IDL.Text, Time, AssignmentType],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDevelopmentPlansForUser' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'assignedToAll' : IDL.Vec(DevelopmentPlan),
            'assignedToMe' : IDL.Vec(DevelopmentPlan),
          }),
        ],
        ['query'],
      ),
    'getFeedbackForUser' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'assignedToAll' : IDL.Vec(FeedbackItem),
            'assignedToMe' : IDL.Vec(FeedbackItem),
          }),
        ],
        ['query'],
      ),
    'getFeedbackFromUser' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'assignedToAll' : IDL.Vec(FeedbackItem),
            'assignedToMe' : IDL.Vec(FeedbackItem),
          }),
        ],
        ['query'],
      ),
    'getGoal' : IDL.Func([IDL.Nat], [IDL.Opt(Goal)], ['query']),
    'getPerformanceReview' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PerformanceReview)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSkillRatings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SkillRating)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCompetencies' : IDL.Func(
        [],
        [
          IDL.Record({
            'assignedToAll' : IDL.Vec(Competency),
            'assignedToMe' : IDL.Vec(Competency),
          }),
        ],
        ['query'],
      ),
    'listGoals' : IDL.Func(
        [],
        [
          IDL.Record({
            'assignedToAll' : IDL.Vec(Goal),
            'assignedToMe' : IDL.Vec(Goal),
          }),
        ],
        ['query'],
      ),
    'listPerformanceReviews' : IDL.Func(
        [],
        [
          IDL.Record({
            'assignedToAll' : IDL.Vec(PerformanceReview),
            'assignedToMe' : IDL.Vec(PerformanceReview),
          }),
        ],
        ['query'],
      ),
    'listUpcomingGoals' : IDL.Func(
        [],
        [
          IDL.Record({
            'assignedToAll' : IDL.Vec(Goal),
            'assignedToMe' : IDL.Vec(Goal),
          }),
        ],
        ['query'],
      ),
    'rateSkill' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPerformanceReview' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          AssignmentType,
        ],
        [IDL.Nat],
        [],
      ),
    'updateDevelopmentPlanStatus' : IDL.Func([IDL.Nat, GoalStatus], [], []),
    'updateGoalStatus' : IDL.Func([IDL.Nat, GoalStatus, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };