/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssignmentType = { 'specificMembers' : Array<Principal> } |
  { 'allMembers' : null };
export type BootstrapAdminResult = { 'adminAlreadyExists' : null } |
  { 'success' : null };
export interface Competency {
  'id' : bigint,
  'assignment' : AssignmentType,
  'name' : string,
  'description' : string,
}
export interface DevelopmentPlan {
  'id' : bigint,
  'status' : GoalStatus,
  'assignment' : AssignmentType,
  'createdBy' : Principal,
  'dueDate' : Time,
  'description' : string,
}
export interface FeedbackItem {
  'id' : bigint,
  'to' : Principal,
  'assignment' : AssignmentType,
  'from' : Principal,
  'comment' : string,
  'timestamp' : Time,
}
export interface Goal {
  'id' : bigint,
  'status' : GoalStatus,
  'title' : string,
  'assignment' : AssignmentType,
  'createdBy' : Principal,
  'description' : string,
  'deadline' : Time,
  'progress' : bigint,
}
export type GoalStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'onHold' : null };
export interface PerformanceReview {
  'id' : bigint,
  'assignment' : AssignmentType,
  'peerAssessment' : Array<string>,
  'selfAssessment' : Array<string>,
  'submittedBy' : Principal,
  'templateName' : string,
  'managerAssessment' : Array<string>,
  'questions' : Array<string>,
}
export interface SkillRating {
  'user' : Principal,
  'rating' : bigint,
  'competencyId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCompetency' : ActorMethod<[string, string, AssignmentType], bigint>,
  'addFeedback' : ActorMethod<[Principal, string, AssignmentType], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdmin' : ActorMethod<[], BootstrapAdminResult>,
  'createDevelopmentPlan' : ActorMethod<[string, Time, AssignmentType], bigint>,
  'createGoal' : ActorMethod<[string, string, Time, AssignmentType], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUserRole' : ActorMethod<[], UserRole>,
  'getDevelopmentPlansForUser' : ActorMethod<
    [Principal],
    {
      'assignedToAll' : Array<DevelopmentPlan>,
      'assignedToMe' : Array<DevelopmentPlan>,
    }
  >,
  'getFeedbackForUser' : ActorMethod<
    [Principal],
    {
      'assignedToAll' : Array<FeedbackItem>,
      'assignedToMe' : Array<FeedbackItem>,
    }
  >,
  'getFeedbackFromUser' : ActorMethod<
    [Principal],
    {
      'assignedToAll' : Array<FeedbackItem>,
      'assignedToMe' : Array<FeedbackItem>,
    }
  >,
  'getGoal' : ActorMethod<[bigint], [] | [Goal]>,
  'getPerformanceReview' : ActorMethod<[bigint], [] | [PerformanceReview]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSkillRatings' : ActorMethod<[Principal], Array<SkillRating>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCompetencies' : ActorMethod<
    [],
    { 'assignedToAll' : Array<Competency>, 'assignedToMe' : Array<Competency> }
  >,
  'listGoals' : ActorMethod<
    [],
    { 'assignedToAll' : Array<Goal>, 'assignedToMe' : Array<Goal> }
  >,
  'listPerformanceReviews' : ActorMethod<
    [],
    {
      'assignedToAll' : Array<PerformanceReview>,
      'assignedToMe' : Array<PerformanceReview>,
    }
  >,
  'listUpcomingGoals' : ActorMethod<
    [],
    { 'assignedToAll' : Array<Goal>, 'assignedToMe' : Array<Goal> }
  >,
  'rateSkill' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPerformanceReview' : ActorMethod<
    [
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      AssignmentType,
    ],
    bigint
  >,
  'updateDevelopmentPlanStatus' : ActorMethod<[bigint, GoalStatus], undefined>,
  'updateGoalStatus' : ActorMethod<[bigint, GoalStatus, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];