/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Competency {
    id: bigint;
    assignment: AssignmentType;
    name: string;
    description: string;
}
export interface SkillRating {
    user: Principal;
    rating: bigint;
    competencyId: bigint;
}
export type Time = bigint;
export interface PerformanceReview {
    id: bigint;
    assignment: AssignmentType;
    peerAssessment: Array<string>;
    selfAssessment: Array<string>;
    submittedBy: Principal;
    templateName: string;
    managerAssessment: Array<string>;
    questions: Array<string>;
}
export interface DevelopmentPlan {
    id: bigint;
    status: GoalStatus;
    assignment: AssignmentType;
    createdBy: Principal;
    dueDate: Time;
    description: string;
}
export type AssignmentType = {
    __kind__: "specificMembers";
    specificMembers: Array<Principal>;
} | {
    __kind__: "allMembers";
    allMembers: null;
};
export interface FeedbackItem {
    id: bigint;
    to: Principal;
    assignment: AssignmentType;
    from: Principal;
    comment: string;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
    email: string;
    department: string;
}
export interface Goal {
    id: bigint;
    status: GoalStatus;
    title: string;
    assignment: AssignmentType;
    createdBy: Principal;
    description: string;
    deadline: Time;
    progress: bigint;
}
export enum BootstrapAdminResult {
    adminAlreadyExists = "adminAlreadyExists",
    success = "success"
}
export enum GoalStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress",
    onHold = "onHold"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCompetency(name: string, description: string, assignment: AssignmentType): Promise<bigint>;
    addFeedback(to: Principal, comment: string, assignment: AssignmentType): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bootstrapAdmin(): Promise<BootstrapAdminResult>;
    createDevelopmentPlan(description: string, dueDate: Time, assignment: AssignmentType): Promise<bigint>;
    createGoal(title: string, description: string, deadline: Time, assignment: AssignmentType): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentUserRole(): Promise<UserRole>;
    getDevelopmentPlansForUser(user: Principal): Promise<{
        assignedToAll: Array<DevelopmentPlan>;
        assignedToMe: Array<DevelopmentPlan>;
    }>;
    getFeedbackForUser(user: Principal): Promise<{
        assignedToAll: Array<FeedbackItem>;
        assignedToMe: Array<FeedbackItem>;
    }>;
    getFeedbackFromUser(user: Principal): Promise<{
        assignedToAll: Array<FeedbackItem>;
        assignedToMe: Array<FeedbackItem>;
    }>;
    getGoal(id: bigint): Promise<Goal | null>;
    getPerformanceReview(id: bigint): Promise<PerformanceReview | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSkillRatings(user: Principal): Promise<Array<SkillRating>>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listCompetencies(): Promise<{
        assignedToAll: Array<Competency>;
        assignedToMe: Array<Competency>;
    }>;
    listGoals(): Promise<{
        assignedToAll: Array<Goal>;
        assignedToMe: Array<Goal>;
    }>;
    listPerformanceReviews(): Promise<{
        assignedToAll: Array<PerformanceReview>;
        assignedToMe: Array<PerformanceReview>;
    }>;
    listUpcomingGoals(): Promise<{
        assignedToAll: Array<Goal>;
        assignedToMe: Array<Goal>;
    }>;
    rateSkill(competencyId: bigint, rating: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPerformanceReview(templateName: string, questions: Array<string>, selfAssessment: Array<string>, managerAssessment: Array<string>, peerAssessment: Array<string>, assignment: AssignmentType): Promise<bigint>;
    updateDevelopmentPlanStatus(id: bigint, status: GoalStatus): Promise<void>;
    updateGoalStatus(id: bigint, status: GoalStatus, progress: bigint): Promise<void>;
}
import type { AssignmentType as _AssignmentType, BootstrapAdminResult as _BootstrapAdminResult, Competency as _Competency, DevelopmentPlan as _DevelopmentPlan, FeedbackItem as _FeedbackItem, Goal as _Goal, GoalStatus as _GoalStatus, PerformanceReview as _PerformanceReview, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCompetency(arg0: string, arg1: string, arg2: AssignmentType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCompetency(arg0, arg1, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCompetency(arg0, arg1, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addFeedback(arg0: Principal, arg1: string, arg2: AssignmentType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeedback(arg0, arg1, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeedback(arg0, arg1, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bootstrapAdmin(): Promise<BootstrapAdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapAdmin();
                return from_candid_BootstrapAdminResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapAdmin();
            return from_candid_BootstrapAdminResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDevelopmentPlan(arg0: string, arg1: Time, arg2: AssignmentType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDevelopmentPlan(arg0, arg1, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDevelopmentPlan(arg0, arg1, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createGoal(arg0: string, arg1: string, arg2: Time, arg3: AssignmentType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, arg2, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, arg2, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDevelopmentPlansForUser(arg0: Principal): Promise<{
        assignedToAll: Array<DevelopmentPlan>;
        assignedToMe: Array<DevelopmentPlan>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevelopmentPlansForUser(arg0);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevelopmentPlansForUser(arg0);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedbackForUser(arg0: Principal): Promise<{
        assignedToAll: Array<FeedbackItem>;
        assignedToMe: Array<FeedbackItem>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackForUser(arg0);
                return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackForUser(arg0);
            return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedbackFromUser(arg0: Principal): Promise<{
        assignedToAll: Array<FeedbackItem>;
        assignedToMe: Array<FeedbackItem>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackFromUser(arg0);
                return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackFromUser(arg0);
            return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoal(arg0: bigint): Promise<Goal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoal(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoal(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceReview(arg0: bigint): Promise<PerformanceReview | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceReview(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceReview(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSkillRatings(arg0: Principal): Promise<Array<SkillRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSkillRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSkillRatings(arg0);
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCompetencies(): Promise<{
        assignedToAll: Array<Competency>;
        assignedToMe: Array<Competency>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listCompetencies();
                return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCompetencies();
            return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGoals(): Promise<{
        assignedToAll: Array<Goal>;
        assignedToMe: Array<Goal>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listGoals();
                return from_candid_record_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGoals();
            return from_candid_record_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPerformanceReviews(): Promise<{
        assignedToAll: Array<PerformanceReview>;
        assignedToMe: Array<PerformanceReview>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listPerformanceReviews();
                return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPerformanceReviews();
            return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUpcomingGoals(): Promise<{
        assignedToAll: Array<Goal>;
        assignedToMe: Array<Goal>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listUpcomingGoals();
                return from_candid_record_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUpcomingGoals();
            return from_candid_record_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async rateSkill(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateSkill(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateSkill(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitPerformanceReview(arg0: string, arg1: Array<string>, arg2: Array<string>, arg3: Array<string>, arg4: Array<string>, arg5: AssignmentType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPerformanceReview(arg0, arg1, arg2, arg3, arg4, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPerformanceReview(arg0, arg1, arg2, arg3, arg4, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateDevelopmentPlanStatus(arg0: bigint, arg1: GoalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDevelopmentPlanStatus(arg0, to_candid_GoalStatus_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDevelopmentPlanStatus(arg0, to_candid_GoalStatus_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateGoalStatus(arg0: bigint, arg1: GoalStatus, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoalStatus(arg0, to_candid_GoalStatus_n36(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoalStatus(arg0, to_candid_GoalStatus_n36(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
}
function from_candid_AssignmentType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentType): AssignmentType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BootstrapAdminResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BootstrapAdminResult): BootstrapAdminResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Competency_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Competency): Competency {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_DevelopmentPlan_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DevelopmentPlan): DevelopmentPlan {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_FeedbackItem_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackItem): FeedbackItem {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_GoalStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalStatus): GoalStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PerformanceReview_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PerformanceReview): PerformanceReview {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Goal]): Goal | null {
    return value.length === 0 ? null : from_candid_Goal_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PerformanceReview]): PerformanceReview | null {
    return value.length === 0 ? null : from_candid_PerformanceReview_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedToAll: Array<_DevelopmentPlan>;
    assignedToMe: Array<_DevelopmentPlan>;
}): {
    assignedToAll: Array<DevelopmentPlan>;
    assignedToMe: Array<DevelopmentPlan>;
} {
    return {
        assignedToAll: from_candid_vec_n11(_uploadFile, _downloadFile, value.assignedToAll),
        assignedToMe: from_candid_vec_n11(_uploadFile, _downloadFile, value.assignedToMe)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _GoalStatus;
    assignment: _AssignmentType;
    createdBy: Principal;
    dueDate: _Time;
    description: string;
}): {
    id: bigint;
    status: GoalStatus;
    assignment: AssignmentType;
    createdBy: Principal;
    dueDate: Time;
    description: string;
} {
    return {
        id: value.id,
        status: from_candid_GoalStatus_n14(_uploadFile, _downloadFile, value.status),
        assignment: from_candid_AssignmentType_n16(_uploadFile, _downloadFile, value.assignment),
        createdBy: value.createdBy,
        dueDate: value.dueDate,
        description: value.description
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedToAll: Array<_FeedbackItem>;
    assignedToMe: Array<_FeedbackItem>;
}): {
    assignedToAll: Array<FeedbackItem>;
    assignedToMe: Array<FeedbackItem>;
} {
    return {
        assignedToAll: from_candid_vec_n19(_uploadFile, _downloadFile, value.assignedToAll),
        assignedToMe: from_candid_vec_n19(_uploadFile, _downloadFile, value.assignedToMe)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: Principal;
    assignment: _AssignmentType;
    from: Principal;
    comment: string;
    timestamp: _Time;
}): {
    id: bigint;
    to: Principal;
    assignment: AssignmentType;
    from: Principal;
    comment: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        to: value.to,
        assignment: from_candid_AssignmentType_n16(_uploadFile, _downloadFile, value.assignment),
        from: value.from,
        comment: value.comment,
        timestamp: value.timestamp
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _GoalStatus;
    title: string;
    assignment: _AssignmentType;
    createdBy: Principal;
    description: string;
    deadline: _Time;
    progress: bigint;
}): {
    id: bigint;
    status: GoalStatus;
    title: string;
    assignment: AssignmentType;
    createdBy: Principal;
    description: string;
    deadline: Time;
    progress: bigint;
} {
    return {
        id: value.id,
        status: from_candid_GoalStatus_n14(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignment: from_candid_AssignmentType_n16(_uploadFile, _downloadFile, value.assignment),
        createdBy: value.createdBy,
        description: value.description,
        deadline: value.deadline,
        progress: value.progress
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assignment: _AssignmentType;
    peerAssessment: Array<string>;
    selfAssessment: Array<string>;
    submittedBy: Principal;
    templateName: string;
    managerAssessment: Array<string>;
    questions: Array<string>;
}): {
    id: bigint;
    assignment: AssignmentType;
    peerAssessment: Array<string>;
    selfAssessment: Array<string>;
    submittedBy: Principal;
    templateName: string;
    managerAssessment: Array<string>;
    questions: Array<string>;
} {
    return {
        id: value.id,
        assignment: from_candid_AssignmentType_n16(_uploadFile, _downloadFile, value.assignment),
        peerAssessment: value.peerAssessment,
        selfAssessment: value.selfAssessment,
        submittedBy: value.submittedBy,
        templateName: value.templateName,
        managerAssessment: value.managerAssessment,
        questions: value.questions
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedToAll: Array<_Competency>;
    assignedToMe: Array<_Competency>;
}): {
    assignedToAll: Array<Competency>;
    assignedToMe: Array<Competency>;
} {
    return {
        assignedToAll: from_candid_vec_n29(_uploadFile, _downloadFile, value.assignedToAll),
        assignedToMe: from_candid_vec_n29(_uploadFile, _downloadFile, value.assignedToMe)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assignment: _AssignmentType;
    name: string;
    description: string;
}): {
    id: bigint;
    assignment: AssignmentType;
    name: string;
    description: string;
} {
    return {
        id: value.id,
        assignment: from_candid_AssignmentType_n16(_uploadFile, _downloadFile, value.assignment),
        name: value.name,
        description: value.description
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedToAll: Array<_Goal>;
    assignedToMe: Array<_Goal>;
}): {
    assignedToAll: Array<Goal>;
    assignedToMe: Array<Goal>;
} {
    return {
        assignedToAll: from_candid_vec_n33(_uploadFile, _downloadFile, value.assignedToAll),
        assignedToMe: from_candid_vec_n33(_uploadFile, _downloadFile, value.assignedToMe)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedToAll: Array<_PerformanceReview>;
    assignedToMe: Array<_PerformanceReview>;
}): {
    assignedToAll: Array<PerformanceReview>;
    assignedToMe: Array<PerformanceReview>;
} {
    return {
        assignedToAll: from_candid_vec_n35(_uploadFile, _downloadFile, value.assignedToAll),
        assignedToMe: from_candid_vec_n35(_uploadFile, _downloadFile, value.assignedToMe)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    onHold: null;
}): GoalStatus {
    return "notStarted" in value ? GoalStatus.notStarted : "completed" in value ? GoalStatus.completed : "inProgress" in value ? GoalStatus.inProgress : "onHold" in value ? GoalStatus.onHold : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    specificMembers: Array<Principal>;
} | {
    allMembers: null;
}): {
    __kind__: "specificMembers";
    specificMembers: Array<Principal>;
} | {
    __kind__: "allMembers";
    allMembers: null;
} {
    return "specificMembers" in value ? {
        __kind__: "specificMembers",
        specificMembers: value.specificMembers
    } : "allMembers" in value ? {
        __kind__: "allMembers",
        allMembers: value.allMembers
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adminAlreadyExists: null;
} | {
    success: null;
}): BootstrapAdminResult {
    return "adminAlreadyExists" in value ? BootstrapAdminResult.adminAlreadyExists : "success" in value ? BootstrapAdminResult.success : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DevelopmentPlan>): Array<DevelopmentPlan> {
    return value.map((x)=>from_candid_DevelopmentPlan_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedbackItem>): Array<FeedbackItem> {
    return value.map((x)=>from_candid_FeedbackItem_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Competency>): Array<Competency> {
    return value.map((x)=>from_candid_Competency_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PerformanceReview>): Array<PerformanceReview> {
    return value.map((x)=>from_candid_PerformanceReview_n26(_uploadFile, _downloadFile, x));
}
function to_candid_AssignmentType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentType): _AssignmentType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_GoalStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalStatus): _GoalStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "specificMembers";
    specificMembers: Array<Principal>;
} | {
    __kind__: "allMembers";
    allMembers: null;
}): {
    specificMembers: Array<Principal>;
} | {
    allMembers: null;
} {
    return value.__kind__ === "specificMembers" ? {
        specificMembers: value.specificMembers
    } : value.__kind__ === "allMembers" ? {
        allMembers: value.allMembers
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalStatus): {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    onHold: null;
} {
    return value == GoalStatus.notStarted ? {
        notStarted: null
    } : value == GoalStatus.completed ? {
        completed: null
    } : value == GoalStatus.inProgress ? {
        inProgress: null
    } : value == GoalStatus.onHold ? {
        onHold: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
